[package]
name = "quickjs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
wasi-common = "7.0.0"
wasmtime = "7.0.0"
wasmtime-wasi = "7.0.0"

[dev-dependencies]
clap = { version = "4.2.1", features = ["derive"] }
num_cpus = "1.15.0"
rayon = "1.7.0"
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false