[package]
name = "quickjs"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasi-common = "10.0.0"
wasmtime = "10.0.0"
wasmtime-wasi = "10.0.0"

[dev-dependencies]
clap = { version = "4.3.5", features = ["derive"] }
num_cpus = "1.15.0"
rayon = "1.7.0"
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false